### ISSUE TITLE
additional-properties support for typed languages

### ISSUE THREAD

**Issue by cmota** [microprofile/microprofile-open-api#688]
Hello all,

We're trying to show on swagger a hashmap that we have in one of our objects:
```
data class ExampleDto(
 val thresholds: Map<String, Set<Double>>
)
```

If we understood correctly, we want to generate something similar to this:

```
ExampleDto:
      type: object
      properties:
        fieldName:
          type: object
          additionalProperties:
            type: array
            items:
              format: double
              type: number
```

From the [documentation](https://swagger.io/docs/specification/v3_0/data-models/dictionaries/) this can be done by using the `additional-properties` function inside `Schema`.

We're using Kotlin Multiplatform to communicate with this library, however since the `additional-properties` function expects a `Class<?>` we're blocked in the above use case, since it's not possible to use in a statically typed language a `Class<*>` as a `Set<Double>`.

Is there any alternative property that we could use to have the desired behaviour? Or is it possible to add that support?

Happy to provide more details or help with testing if needed.
Thanks in advance!

**Comment by MikeEdgar** [comment]
Hi @cmota what schema is being generated for the `Map<String, Set<Double>>` in your example?

**Comment by cmota** [comment]
Hello @MikeEdgar,

Thank you for the quick reply!

It generates this:

````
 properties:
        fields:
          type: object
          additionalProperties:
            type: object
```
