### ISSUE TITLE
Missing usage of examples ExampleObject[] in @Header annotation

### ISSUE THREAD

**Issue by vietk** [microprofile/microprofile-open-api#697]
Hello 

I wanted to generate simple examples using OpenAPI annotations.
It's work well for API responses/Parameter/RequestBody examples.

However there's another place where @ExampleOjbect seems to be allowed in OAS 3.1, it would be in the @Header annotation mapping an [OAS header](https://spec.openapis.org/oas/v3.1.0.html#header-object) object.

It's written that : 
> The Header Object follows the structure of the [Parameter Object](https://spec.openapis.org/oas/v3.1.0.html#parameter-object)

Then, to me it's acceptable to have a way to provide ExampleObject[] inside a @Header, however I don't see any property to allow me mapping ExampleObject[] to a specific header.

I already tried what has been provided in [this change](https://github.com/smallrye/smallrye-open-api/pull/341/commits/9647fec782880b54d01182057ca967215fa316ad) but the corresponding generation is an array of example which is not valid OAS is waiting for a dictionnary : 

valid:
```yaml
  headers:
    Location:
      schema:
        type: string
        format: uri
      examples:
        valid_example:
          value: "/object/1"
```
not valid:
```yaml
  headers:
    Location:
      schema:
        type: string
        format: uri
      examples:
       - not_valid_example:
            value: "/object/1"
```

What maintainer's view on that? 

Regards
Kevin
